-- MySQL Script generated by MySQL Workbench
-- Mon Sep 30 13:44:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cars` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dormitories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dormitories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dormitories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `room` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dean`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dean` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dean` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Thesis_Supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Thesis_Supervisor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Thesis_Supervisor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Grades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Grades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `na` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Animals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Animals` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Animals` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `species` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scholarship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Scholarship` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Scholarship` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amout` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `Cars_id` INT NOT NULL,
  `Dormitories_id` INT NOT NULL,
  `Dean_id` INT NOT NULL,
  `Thesis_Supervisor_id` INT NOT NULL,
  `Grades_id` INT NOT NULL,
  `Animals_id` INT NOT NULL,
  `Scholarship_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Students_Cars_idx` (`Cars_id` ASC) VISIBLE,
  INDEX `fk_Students_Dormitories1_idx` (`Dormitories_id` ASC) VISIBLE,
  INDEX `fk_Students_Dean1_idx` (`Dean_id` ASC) VISIBLE,
  INDEX `fk_Students_Thesis_Supervisor1_idx` (`Thesis_Supervisor_id` ASC) VISIBLE,
  INDEX `fk_Students_Grades1_idx` (`Grades_id` ASC) VISIBLE,
  INDEX `fk_Students_Animals1_idx` (`Animals_id` ASC) VISIBLE,
  INDEX `fk_Students_Scholarship1_idx` (`Scholarship_id` ASC) VISIBLE,
  CONSTRAINT `fk_Students_Cars`
    FOREIGN KEY (`Cars_id`)
    REFERENCES `mydb`.`Cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Dormitories1`
    FOREIGN KEY (`Dormitories_id`)
    REFERENCES `mydb`.`Dormitories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Dean1`
    FOREIGN KEY (`Dean_id`)
    REFERENCES `mydb`.`Dean` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Thesis_Supervisor1`
    FOREIGN KEY (`Thesis_Supervisor_id`)
    REFERENCES `mydb`.`Thesis_Supervisor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Grades1`
    FOREIGN KEY (`Grades_id`)
    REFERENCES `mydb`.`Grades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Animals1`
    FOREIGN KEY (`Animals_id`)
    REFERENCES `mydb`.`Animals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Scholarship1`
    FOREIGN KEY (`Scholarship_id`)
    REFERENCES `mydb`.`Scholarship` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students_has_Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students_has_Courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students_has_Courses` (
  `Students_id` INT NOT NULL,
  `Courses_id` INT NOT NULL,
  PRIMARY KEY (`Students_id`, `Courses_id`),
  INDEX `fk_Students_has_Courses_Courses1_idx` (`Courses_id` ASC) VISIBLE,
  INDEX `fk_Students_has_Courses_Students1_idx` (`Students_id` ASC) VISIBLE,
  CONSTRAINT `fk_Students_has_Courses_Students1`
    FOREIGN KEY (`Students_id`)
    REFERENCES `mydb`.`Students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_has_Courses_Courses1`
    FOREIGN KEY (`Courses_id`)
    REFERENCES `mydb`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fileds_Of_Study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fileds_Of_Study` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fileds_Of_Study` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students_has_Filed_Of_Study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students_has_Filed_Of_Study` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students_has_Filed_Of_Study` (
  `Students_id` INT NOT NULL,
  `Filed_Of_Study_id` INT NOT NULL,
  PRIMARY KEY (`Students_id`, `Filed_Of_Study_id`),
  INDEX `fk_Students_has_Filed_Of_Study_Filed_Of_Study1_idx` (`Filed_Of_Study_id` ASC) VISIBLE,
  INDEX `fk_Students_has_Filed_Of_Study_Students1_idx` (`Students_id` ASC) VISIBLE,
  CONSTRAINT `fk_Students_has_Filed_Of_Study_Students1`
    FOREIGN KEY (`Students_id`)
    REFERENCES `mydb`.`Students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_has_Filed_Of_Study_Filed_Of_Study1`
    FOREIGN KEY (`Filed_Of_Study_id`)
    REFERENCES `mydb`.`Fileds_Of_Study` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Academic_Circles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Academic_Circles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Academic_Circles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students_has_Academic_Circles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students_has_Academic_Circles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students_has_Academic_Circles` (
  `Students_id` INT NOT NULL,
  `Academic_Circles_id` INT NOT NULL,
  PRIMARY KEY (`Students_id`, `Academic_Circles_id`),
  INDEX `fk_Students_has_Academic_Circles_Academic_Circles1_idx` (`Academic_Circles_id` ASC) VISIBLE,
  INDEX `fk_Students_has_Academic_Circles_Students1_idx` (`Students_id` ASC) VISIBLE,
  CONSTRAINT `fk_Students_has_Academic_Circles_Students1`
    FOREIGN KEY (`Students_id`)
    REFERENCES `mydb`.`Students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_has_Academic_Circles_Academic_Circles1`
    FOREIGN KEY (`Academic_Circles_id`)
    REFERENCES `mydb`.`Academic_Circles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Borrowed_Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Borrowed_Books` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Borrowed_Books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `return_time` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students_has_Borrowed_Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students_has_Borrowed_Books` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students_has_Borrowed_Books` (
  `Students_id` INT NOT NULL,
  `Borrowed_Books_id` INT NOT NULL,
  PRIMARY KEY (`Students_id`, `Borrowed_Books_id`),
  INDEX `fk_Students_has_Borrowed_Books_Borrowed_Books1_idx` (`Borrowed_Books_id` ASC) VISIBLE,
  INDEX `fk_Students_has_Borrowed_Books_Students1_idx` (`Students_id` ASC) VISIBLE,
  CONSTRAINT `fk_Students_has_Borrowed_Books_Students1`
    FOREIGN KEY (`Students_id`)
    REFERENCES `mydb`.`Students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_has_Borrowed_Books_Borrowed_Books1`
    FOREIGN KEY (`Borrowed_Books_id`)
    REFERENCES `mydb`.`Borrowed_Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Events` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `ticket_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students_has_Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students_has_Events` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students_has_Events` (
  `Students_id` INT NOT NULL,
  `Events_id` INT NOT NULL,
  PRIMARY KEY (`Students_id`, `Events_id`),
  INDEX `fk_Students_has_Events_Events1_idx` (`Events_id` ASC) VISIBLE,
  INDEX `fk_Students_has_Events_Students1_idx` (`Students_id` ASC) VISIBLE,
  CONSTRAINT `fk_Students_has_Events_Students1`
    FOREIGN KEY (`Students_id`)
    REFERENCES `mydb`.`Students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_has_Events_Events1`
    FOREIGN KEY (`Events_id`)
    REFERENCES `mydb`.`Events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
